package com.gitmob.app.ui.reporeleases

import android.provider.OpenableColumns
import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.ArrowBack
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.material3.pulltorefresh.PullToRefreshBox
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextOverflow
import androidx.compose.ui.unit.dp
import androidx.hilt.lifecycle.viewmodel.compose.hiltViewModel
import androidx.lifecycle.compose.collectAsStateWithLifecycle
import com.gitmob.app.R
import com.gitmob.app.core.permission.RepoPermission
import com.gitmob.app.data.model.*
import com.gitmob.app.ui.common.MarkdownWebView

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun RepoReleaseListScreen(owner: String, name: String, permission: RepoPermission?, onBack: () -> Unit, onReleaseClick: (String) -> Unit, onCreate: () -> Unit, viewModel: RepoReleaseListViewModel = hiltViewModel()) {
    LaunchedEffect(owner, name) { viewModel.init(owner, name, permission) }; val state by viewModel.state.collectAsStateWithLifecycle(); var delete by remember { mutableStateOf<RepoRelease?>(null) }
    Scaffold(topBar = { TopAppBar(title = { Text(stringResource(R.string.repo_releases)) }, navigationIcon = { IconButton(onClick = onBack) { Icon(Icons.AutoMirrored.Filled.ArrowBack, stringResource(R.string.common_back)) } }, actions = { if (state.capabilities.canPush) IconButton(onClick = onCreate) { Icon(Icons.Default.Add, stringResource(R.string.release_new)) } }, windowInsets = WindowInsets.safeDrawing.only(WindowInsetsSides.Top + WindowInsetsSides.Horizontal)) }, contentWindowInsets = WindowInsets.safeDrawing.only(WindowInsetsSides.Top + WindowInsetsSides.Horizontal)) { padding ->
        PullToRefreshBox(state.isLoading && state.releases.isNotEmpty(), viewModel::refresh, Modifier.fillMaxSize().padding(padding)) { when { state.isLoading && state.releases.isEmpty() -> CircularProgressIndicator(Modifier.align(Alignment.Center)); state.loadFailed -> ReleaseRetry(viewModel::retry); state.releases.isEmpty() -> Text(stringResource(R.string.release_empty), modifier = Modifier.align(Alignment.Center)); else -> LazyColumn { items(state.releases, key = { it.id }) { release -> ReleaseRow(release, state.capabilities.canPush, { onReleaseClick(release.tagName) }) { delete = release }; HorizontalDivider() }; if (state.hasNextPage) item { LaunchedEffect(state.releases.size) { viewModel.loadMore() } } } } }
    }
    delete?.let { release -> AlertDialog(onDismissRequest = { delete = null }, title = { Text(stringResource(R.string.release_delete_title)) }, text = { Text(stringResource(R.string.release_delete_message)) }, dismissButton = { TextButton(onClick = { delete = null }) { Text(stringResource(R.string.common_cancel)) } }, confirmButton = { TextButton(onClick = { viewModel.delete(release) { delete = null } }) { Text(stringResource(R.string.common_delete), color = MaterialTheme.colorScheme.error) } }) }
}

@Composable private fun ReleaseRow(release: RepoRelease, canManage: Boolean, click: () -> Unit, delete: () -> Unit) { Column(Modifier.fillMaxWidth().clickable(onClick = click).padding(16.dp), verticalArrangement = Arrangement.spacedBy(5.dp)) { Row(verticalAlignment = Alignment.CenterVertically) { Icon(if (release.draft) Icons.Default.Drafts else Icons.Default.Sell, null, tint = MaterialTheme.colorScheme.primary); Spacer(Modifier.width(10.dp)); Column(Modifier.weight(1f)) { Text(release.name ?: release.tagName, fontWeight = FontWeight.SemiBold, maxLines = 2, overflow = TextOverflow.Ellipsis); Text(release.tagName, style = MaterialTheme.typography.bodySmall); Text(stringResource(if (release.draft) R.string.release_draft else if (release.prerelease) R.string.release_prerelease else R.string.release_published), style = MaterialTheme.typography.labelSmall) }; if (canManage) IconButton(onClick = delete) { Icon(Icons.Default.Delete, stringResource(R.string.common_delete)) } }; Text(stringResource(R.string.release_assets_count, release.assets.size), style = MaterialTheme.typography.bodySmall, color = MaterialTheme.colorScheme.onSurfaceVariant) } }

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun RepoReleaseDetailScreen(owner: String, name: String, tag: String?, releaseId: Long?, permission: RepoPermission?, onBack: () -> Unit, onEdit: (Long) -> Unit, viewModel: RepoReleaseDetailViewModel = hiltViewModel()) {
    LaunchedEffect(owner, name, tag, releaseId) { viewModel.init(owner, name, tag, releaseId, permission) }; val state by viewModel.state.collectAsStateWithLifecycle(); val context = LocalContext.current; var menu by remember { mutableStateOf(false) }; var editorAsset by remember { mutableStateOf<RepoReleaseAsset?>(null) }
    val picker = rememberLauncherForActivityResult(ActivityResultContracts.OpenDocument()) { uri -> uri ?: return@rememberLauncherForActivityResult; val bytes = context.contentResolver.openInputStream(uri)?.use { it.readBytes() } ?: return@rememberLauncherForActivityResult; val fileName = context.contentResolver.query(uri, arrayOf(OpenableColumns.DISPLAY_NAME), null, null, null)?.use { cursor -> if (cursor.moveToFirst()) cursor.getString(0) else "asset.bin" } ?: "asset.bin"; viewModel.uploadAsset(fileName, null, context.contentResolver.getType(uri) ?: "application/octet-stream", bytes) }
    Scaffold(topBar = { TopAppBar(title = { Text(state.release?.name ?: state.release?.tagName ?: stringResource(R.string.repo_releases)) }, navigationIcon = { IconButton(onClick = onBack) { Icon(Icons.AutoMirrored.Filled.ArrowBack, stringResource(R.string.common_back)) } }, actions = { state.release?.let { release -> Box { IconButton(onClick = { menu = true }) { Icon(Icons.Default.MoreVert, stringResource(R.string.issue_more)) }; DropdownMenu(menu, { menu = false }) { if (state.capabilities.canPush) DropdownMenuItem(text = { Text(stringResource(R.string.common_edit)) }, onClick = { menu = false; onEdit(release.id) }); if (state.capabilities.canPush) DropdownMenuItem(text = { Text(stringResource(R.string.release_delete), color = MaterialTheme.colorScheme.error) }, onClick = { menu = false; viewModel.confirmDelete(true) }) } } } }, windowInsets = WindowInsets.safeDrawing.only(WindowInsetsSides.Top + WindowInsetsSides.Horizontal)) }, contentWindowInsets = WindowInsets.safeDrawing.only(WindowInsetsSides.Top + WindowInsetsSides.Horizontal)) { padding ->
        when { state.isLoading && state.release == null -> Box(Modifier.fillMaxSize().padding(padding), contentAlignment = Alignment.Center) { CircularProgressIndicator() }; state.loadFailed -> ReleaseRetry(viewModel::retry); state.release != null -> LazyColumn(Modifier.fillMaxSize().padding(padding), contentPadding = PaddingValues(bottom = 24.dp)) { item { val release = state.release!!; Column(Modifier.padding(16.dp), verticalArrangement = Arrangement.spacedBy(8.dp)) { Text(release.name ?: release.tagName, style = MaterialTheme.typography.headlineSmall, fontWeight = FontWeight.SemiBold); Text("${release.tagName} · ${release.targetCommitish}"); Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) { AssistChip(onClick = {}, label = { Text(stringResource(if (release.draft) R.string.release_draft else if (release.prerelease) R.string.release_prerelease else R.string.release_published)) }); Text(release.publishedAt?.take(10) ?: release.createdAt.take(10)) } }; if (release.bodyHtml?.isNotBlank() == true) MarkdownWebView(release.bodyHtml, Modifier.fillMaxWidth()) else Text(release.body, modifier = Modifier.padding(horizontal = 16.dp)) }; item { Row(Modifier.fillMaxWidth().padding(16.dp), verticalAlignment = Alignment.CenterVertically) { Text(stringResource(R.string.release_assets), style = MaterialTheme.typography.titleMedium, modifier = Modifier.weight(1f)); if (state.capabilities.canPush) IconButton(onClick = { picker.launch(arrayOf("*/*")) }) { Icon(Icons.Default.UploadFile, stringResource(R.string.release_upload_asset)) } } }; items(state.release!!.assets, key = { it.id }) { asset -> val opening = asset.id in state.openingAssetIds; ListItem(headlineContent = { Text(asset.name) }, supportingContent = { Text(stringResource(R.string.release_asset_meta, asset.downloadCount, asset.size)) }, trailingContent = { Row { if (state.capabilities.canPush) IconButton(onClick = { editorAsset = asset }) { Icon(Icons.Default.Edit, stringResource(R.string.common_edit)) }; IconButton(onClick = { viewModel.downloadAsset(asset) }, enabled = !opening) { if (opening) CircularProgressIndicator(Modifier.size(20.dp), strokeWidth = 2.dp) else Icon(Icons.Default.Download, stringResource(R.string.common_download)) }; if (state.capabilities.canPush) IconButton(onClick = { viewModel.confirmDeleteAsset(asset) }) { Icon(Icons.Default.Delete, stringResource(R.string.common_delete)) } } }) } } }
    }
    if (state.pendingDelete) AlertDialog(onDismissRequest = { viewModel.confirmDelete(false) }, title = { Text(stringResource(R.string.release_delete_title)) }, text = { Text(stringResource(R.string.release_delete_message)) }, dismissButton = { TextButton(onClick = { viewModel.confirmDelete(false) }) { Text(stringResource(R.string.common_cancel)) } }, confirmButton = { TextButton(onClick = { viewModel.delete(onBack) }) { Text(stringResource(R.string.common_delete), color = MaterialTheme.colorScheme.error) } })
    state.pendingDeleteAsset?.let { asset -> AlertDialog(onDismissRequest = { viewModel.confirmDeleteAsset(null) }, title = { Text(stringResource(R.string.release_delete_asset_title)) }, text = { Text(asset.name) }, dismissButton = { TextButton(onClick = { viewModel.confirmDeleteAsset(null) }) { Text(stringResource(R.string.common_cancel)) } }, confirmButton = { TextButton(onClick = viewModel::deleteAsset) { Text(stringResource(R.string.common_delete), color = MaterialTheme.colorScheme.error) } }) }
    editorAsset?.let { asset -> ReleaseAssetEditDialog(asset, { editorAsset = null }) { fileName, label -> viewModel.updateAsset(asset, fileName, label) { editorAsset = null } } }
}

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun RepoReleaseEditorScreen(owner: String, name: String, releaseId: Long?, permission: RepoPermission?, onBack: () -> Unit, onSaved: (String) -> Unit, viewModel: RepoReleaseEditorViewModel = hiltViewModel()) {
    LaunchedEffect(owner, name, releaseId, permission) { viewModel.init(owner, name, releaseId, permission) }; val state by viewModel.state.collectAsStateWithLifecycle(); val existing = state.existing; var tag by remember(existing) { mutableStateOf(existing?.tagName.orEmpty()) }; var target by remember(existing) { mutableStateOf(existing?.targetCommitish.orEmpty()) }; var title by remember(existing) { mutableStateOf(existing?.name.orEmpty()) }; var body by remember(existing) { mutableStateOf(existing?.body.orEmpty()) }; var draft by remember(existing) { mutableStateOf(existing?.draft ?: true) }; var prerelease by remember(existing) { mutableStateOf(existing?.prerelease ?: false) }
    Scaffold(topBar = { TopAppBar(title = { Text(stringResource(if (releaseId == null) R.string.release_new else R.string.release_edit)) }, navigationIcon = { IconButton(onClick = onBack) { Icon(Icons.AutoMirrored.Filled.ArrowBack, stringResource(R.string.common_back)) } }, windowInsets = WindowInsets.safeDrawing.only(WindowInsetsSides.Top + WindowInsetsSides.Horizontal)) }, contentWindowInsets = WindowInsets.safeDrawing.only(WindowInsetsSides.Top + WindowInsetsSides.Horizontal)) { padding -> LazyColumn(Modifier.fillMaxSize().padding(padding), contentPadding = PaddingValues(16.dp), verticalArrangement = Arrangement.spacedBy(12.dp)) { item { OutlinedTextField(tag, { tag = it }, label = { Text(stringResource(R.string.release_tag)) }, singleLine = true, modifier = Modifier.fillMaxWidth()) }; item { OutlinedTextField(target, { target = it }, label = { Text(stringResource(R.string.release_target)) }, singleLine = true, modifier = Modifier.fillMaxWidth()) }; item { OutlinedTextField(title, { title = it }, label = { Text(stringResource(R.string.release_title)) }, singleLine = true, modifier = Modifier.fillMaxWidth()) }; item { TextButton(onClick = { viewModel.generateNotes(tag, target) { notes -> body = notes.body; if (title.isBlank()) title = notes.name.orEmpty() } }, enabled = tag.isNotBlank()) { Icon(Icons.Default.AutoAwesome, null); Text(stringResource(R.string.release_generate_notes)) } }; item { OutlinedTextField(body, { body = it }, label = { Text(stringResource(R.string.release_notes)) }, minLines = 10, modifier = Modifier.fillMaxWidth()) }; item { Row(verticalAlignment = Alignment.CenterVertically) { Checkbox(draft, { draft = it }); Text(stringResource(R.string.release_draft)) } }; item { Row(verticalAlignment = Alignment.CenterVertically) { Checkbox(prerelease, { prerelease = it }); Text(stringResource(R.string.release_prerelease)) } }; item { Row(Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.End) { TextButton(onClick = onBack) { Text(stringResource(R.string.common_cancel)) }; Button(onClick = { viewModel.save(SaveRepoReleaseInput(tag, target, title.ifBlank { null }, body, draft, prerelease)) { onSaved(it.tagName) } }, enabled = state.capabilities.canPush && tag.isNotBlank() && !state.isSaving) { Text(stringResource(R.string.common_save)) } } } } }
}

@Composable private fun ReleaseAssetEditDialog(asset: RepoReleaseAsset, dismiss: () -> Unit, save: (String, String?) -> Unit) { var name by remember(asset) { mutableStateOf(asset.name) }; var label by remember(asset) { mutableStateOf(asset.label.orEmpty()) }; AlertDialog(onDismissRequest = dismiss, title = { Text(stringResource(R.string.release_edit_asset)) }, text = { Column(verticalArrangement = Arrangement.spacedBy(8.dp)) { OutlinedTextField(name, { name = it }, label = { Text(stringResource(R.string.release_asset_name)) }); OutlinedTextField(label, { label = it }, label = { Text(stringResource(R.string.release_asset_label)) }) } }, dismissButton = { TextButton(onClick = dismiss) { Text(stringResource(R.string.common_cancel)) } }, confirmButton = { Button(onClick = { save(name, label.ifBlank { null }) }, enabled = name.isNotBlank()) { Text(stringResource(R.string.common_save)) } }) }
@Composable private fun ReleaseRetry(retry: () -> Unit) { Column(Modifier.fillMaxSize(), horizontalAlignment = Alignment.CenterHorizontally, verticalArrangement = Arrangement.Center) { Text(stringResource(R.string.common_load_failed)); Button(onClick = retry) { Text(stringResource(R.string.common_retry)) } } }
